# ESP32-8048S070 Board Configuration - Enhanced OBD2 Dashboard - UPDATED
CONFIG_IDF_TARGET="esp32s3"

# ESP32-S3 CPU Configuration
CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=y
CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ=240
CONFIG_ESP32S3_REV_MIN_FULL=0
CONFIG_ESP32S3_REV_MIN=0

# Memory Configuration for ESP32-8048S070 (8MB PSRAM)
CONFIG_ESP32S3_SPIRAM_SUPPORT=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_TYPE_ESPPSRAM64=y
CONFIG_SPIRAM_SPEED_80M=y
CONFIG_SPIRAM_USE_MALLOC=y
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP=y

# USB Configuration (GPIO20 dedicated to USB D+) - UPDATED
CONFIG_TINYUSB_ENABLED=y
CONFIG_TINYUSB_CDC_ENABLED=y
CONFIG_TINYUSB_CDC_COUNT=2
CONFIG_USB_OTG_SUPPORTED=y
CONFIG_USB_HOST_ENABLED=y
CONFIG_USB_HOST_CDC_ACM_ENABLED=y
CONFIG_TINYUSB_DEBUG_LEVEL=2

# USB Host specific settings - UPDATED
CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE=512
CONFIG_USB_HOST_HW_BUFFER_BIAS_BALANCED=y
CONFIG_USB_HOST_TASK_STACK_SIZE=4096
CONFIG_USB_HOST_TASK_PRIORITY=2

# Alternative: Use UART for USB bridge if GPIO20 conflict
CONFIG_ESP_CONSOLE_UART_DEFAULT=y
CONFIG_ESP_CONSOLE_UART_NUM=0

# FreeRTOS Configuration - UPDATED
CONFIG_FREERTOS_HZ=1000
CONFIG_FREERTOS_USE_TRACE_FACILITY=y
CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=y
CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID=y
CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH=3072
CONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=30
CONFIG_FREERTOS_IDLE_TASK_STACKSIZE=2048

# Flash Configuration (16MB Flash on ESP32-8048S070)
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESPTOOLPY_FLASHFREQ_80M=y
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y

# Partition Table
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"

# ADC Configuration
CONFIG_ADC_ONESHOT_CTRL_FUNC_IN_IRAM=y
CONFIG_ADC_CAL_EFUSE_TP_ENABLE=y
CONFIG_ADC_CAL_EFUSE_VREF_ENABLE=y

# I2C Configuration (for GT911 touch controller) - UPDATED
CONFIG_I2C_ENABLE_DEBUG_LOG=y
CONFIG_I2C_MASTER_ISR_IN_IRAM=y

# GPIO Configuration (for touch interrupt) - UPDATED
CONFIG_GPIO_ESP32_SUPPORT_SWITCH_SLP_PULL=y

# SPI Configuration
CONFIG_SPI_MASTER_IN_IRAM=y
CONFIG_SPI_MASTER_ISR_IN_IRAM=y

# RGB LCD Configuration (15-bit mode) - UPDATED
CONFIG_LCD_PANEL_IO_FORMAT_BUF_SIZE=32
CONFIG_LCD_RGB_ISR_IRAM_SAFE=y
CONFIG_LCD_RGB_RESTART_IN_VSYNC=y
CONFIG_LCD_RGB_ELEMENT_ORDER_RGB=y

# LVGL Configuration for 15-bit display with touch - UPDATED
CONFIG_LV_USE_LOG=y
CONFIG_LV_LOG_LEVEL_WARN=y
CONFIG_LV_MEM_CUSTOM=y
CONFIG_LV_MEM_SIZE=262144
CONFIG_LV_TICK_CUSTOM=y
CONFIG_LV_DISP_DEF_REFR_PERIOD=30
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=n
CONFIG_LV_USE_PERF_MONITOR=y
CONFIG_LV_USE_MEM_MONITOR=y

# Touch Input Configuration - UPDATED
CONFIG_LV_USE_INDEV=y
CONFIG_LV_INDEV_DEF_READ_PERIOD=30
CONFIG_LV_INDEV_DEF_DRAG_LIMIT=10
CONFIG_LV_INDEV_DEF_DRAG_THROW=10
CONFIG_LV_INDEV_DEF_LONG_PRESS_TIME=400
CONFIG_LV_INDEV_DEF_LONG_PRESS_REP_TIME=100
CONFIG_LV_INDEV_DEF_GESTURE_LIMIT=50
CONFIG_LV_INDEV_DEF_GESTURE_MIN_VELOCITY=3

# Compiler options
CONFIG_COMPILER_OPTIMIZATION_SIZE=y
CONFIG_COMPILER_CXX_EXCEPTIONS=y
CONFIG_COMPILER_CXX_RTTI=y

# Logging - UPDATED
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
CONFIG_LOG_MAXIMUM_LEVEL_VERBOSE=y
CONFIG_LOG_COLORS=y

# Task Watchdog - UPDATED
CONFIG_ESP_TASK_WDT_TIMEOUT_S=30
CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0=y
CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1=y

# System Configuration - UPDATED
CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE=32
CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=2304
CONFIG_ESP_MAIN_TASK_STACK_SIZE=8192
CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0=y

# NVS Configuration - NEW
CONFIG_NVS_ENCRYPTION=n
CONFIG_NVS_MAX_BLOB_SIZE=4096

# Performance Configuration - NEW
CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB=y
CONFIG_ESP32S3_DATA_CACHE_32KB=y
CONFIG_ESP32S3_DATA_CACHE_LINE_32B=y

# Error Handling Configuration - NEW
CONFIG_ESP_ERR_TO_NAME_LOOKUP=y
CONFIG_ESP_SYSTEM_PANIC_PRINT_HALT=y
CONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=y
CONFIG_ESP_COREDUMP_DATA_FORMAT_ELF=y# ESP32-8048S070 Board Configuration - 7" RGB Display Board
CONFIG_IDF_TARGET="esp32s3"

# ESP32-S3 CPU Configuration
CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=y
CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ=240
CONFIG_ESP32S3_REV_MIN_FULL=0
CONFIG_ESP32S3_REV_MIN=0

# Memory Configuration for ESP32-8048S070 (8MB PSRAM)
CONFIG_ESP32S3_SPIRAM_SUPPORT=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_TYPE_ESPPSRAM64=y
CONFIG_SPIRAM_SPEED_80M=y
CONFIG_SPIRAM_USE_MALLOC=y
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP=y

# USB Configuration (GPIO20 dedicated to USB D+)
CONFIG_TINYUSB_ENABLED=y
CONFIG_TINYUSB_CDC_ENABLED=y
CONFIG_TINYUSB_CDC_COUNT=2
CONFIG_USB_OTG_SUPPORTED=y
CONFIG_USB_HOST_ENABLED=y
CONFIG_USB_HOST_CDC_ACM_ENABLED=y
CONFIG_TINYUSB_DEBUG_LEVEL=2

# USB Host specific settings
CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE=512
CONFIG_USB_HOST_HW_BUFFER_BIAS_BALANCED=y

# Alternative: Use UART for USB bridge if GPIO20 conflict
CONFIG_ESP_CONSOLE_UART_DEFAULT=y
CONFIG_ESP_CONSOLE_UART_NUM=0

# FreeRTOS Configuration
CONFIG_FREERTOS_HZ=1000
CONFIG_FREERTOS_USE_TRACE_FACILITY=y
CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=y
CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID=y
CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH=3072

# Flash Configuration (16MB Flash on ESP32-8048S070)
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESPTOOLPY_FLASHFREQ_80M=y
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y

# Partition Table
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"

# ADC Configuration
CONFIG_ADC_ONESHOT_CTRL_FUNC_IN_IRAM=y
CONFIG_ADC_CAL_EFUSE_TP_ENABLE=y
CONFIG_ADC_CAL_EFUSE_VREF_ENABLE=y

# I2C Configuration (for GT911 touch)
CONFIG_I2C_ENABLE_DEBUG_LOG=y

# SPI Configuration
CONFIG_SPI_MASTER_IN_IRAM=y
CONFIG_SPI_MASTER_ISR_IN_IRAM=y

# RGB LCD Configuration (15-bit mode)
CONFIG_LCD_PANEL_IO_FORMAT_BUF_SIZE=32
CONFIG_LCD_RGB_ISR_IRAM_SAFE=y
CONFIG_LCD_RGB_RESTART_IN_VSYNC=y
CONFIG_LCD_RGB_ELEMENT_ORDER_RGB=y

# LVGL Configuration for 15-bit display (mapped to 16-bit)
CONFIG_LV_USE_LOG=y
CONFIG_LV_LOG_LEVEL_WARN=y
CONFIG_LV_MEM_CUSTOM=y
CONFIG_LV_MEM_SIZE=262144
CONFIG_LV_TICK_CUSTOM=y
CONFIG_LV_DISP_DEF_REFR_PERIOD=30
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=n

# Compiler options
CONFIG_COMPILER_OPTIMIZATION_SIZE=y
CONFIG_COMPILER_CXX_EXCEPTIONS=y
CONFIG_COMPILER_CXX_RTTI=y

# Logging
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
CONFIG_LOG_MAXIMUM_LEVEL_VERBOSE=y
CONFIG_LOG_COLORS=y

# Task Watchdog
CONFIG_ESP_TASK_WDT_TIMEOUT_S=10
CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0=y
CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1=y